#!/bin/bash
# Licensed under the GNU General Public License Version 2
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
####################################################################################################
## Authored by Anthony Nordquist. https://github.com/SalineOS salinelinux@gmail.com 
## Copyright 2013 Anthony Nordquist

## End all running versions and exit if search all the things was already running

ToKill=$(pgrep -f "yad --icons --height=600 --width=900 --single-click --skip-taskbar --on-top --skip-taskbar --undecorated")

if [ "$ToKill" != "" ]; then
 kill $ToKill
 exit 0
fi

yad --icons --height="600" --width="900" --single-click --skip-taskbar --on-top --skip-taskbar --undecorated --read-dir="/usr/share/search-all-the-things/DesktopFiles" --button=$"gtk-quit:3"

exit  